[workspace]
members = [
    "services/old-architecture",
    "services/merchant-simulator",
    "services/new-architecture/api-service",
    "services/new-architecture/data-service",
    "services/new-architecture/webhook-consumer",
]

resolver = "2"
